"""Design tokens centralisés (espacements, tailles, polices, couleurs)."""

from __future__ import annotations

# Espacements uniformes (px)
SPACING_SMALL = 4
SPACING_MEDIUM = 8
SPACING_LARGE = 16
SPACING_XLARGE = 24

# Bornes des panneaux (px)
PANEL_MIN_WIDTH = 160
PANEL_MAX_WIDTH = 480
PANEL_MIN_HEIGHT = 120

# Layout spécifique feature 005
HEADER_HEIGHT = 52
DROP_ZONE_COMPACT_HEIGHT = 110
DROP_ZONE_PREVIEW_MAX_HEIGHT = 220
OPTIONS_PANEL_WIDTH = 260
OPTIONS_PANEL_MIN_WIDTH = 240
OPTIONS_PANEL_MAX_WIDTH = 320
SIDE_TABS_MIN_WIDTH = 280
ACTION_BAR_HEIGHT = 52

# Typographie
FONT_FAMILY = '"Segoe UI", "Helvetica Neue", Arial, sans-serif'
FONT_SIZE_SMALL = 11
FONT_SIZE_BODY = 13
FONT_SIZE_TITLE = 15
FONT_SIZE_HEADING = 18
FONT_WEIGHT_NORMAL = 400
FONT_WEIGHT_LABEL = 500
FONT_WEIGHT_BUTTON = 600
FONT_WEIGHT_TITLE = 700

# Couleurs — thème clair
COLOR_LIGHT_BG = "#fafafa"
COLOR_LIGHT_SURFACE = "#ffffff"
COLOR_LIGHT_BORDER = "#d1d5db"
COLOR_LIGHT_TEXT = "#1f2937"
COLOR_LIGHT_TEXT_MUTED = "#4b5563"
COLOR_LIGHT_PRIMARY = "#2563eb"
COLOR_LIGHT_PRIMARY_HOVER = "#1d4ed8"
COLOR_LIGHT_PRIMARY_PRESSED = "#1e40af"
COLOR_LIGHT_DISABLED_BG = "#cbd5e1"
COLOR_LIGHT_DISABLED_TEXT = "#64748b"
COLOR_LIGHT_SECONDARY_BG = "#e2e8f0"
COLOR_LIGHT_SECONDARY_HOVER = "#cbd5e1"

# Couleurs — thème sombre
COLOR_DARK_BG = "#111827"
COLOR_DARK_SURFACE = "#1f2937"
COLOR_DARK_BORDER = "#374151"
COLOR_DARK_TEXT = "#e5e7eb"
COLOR_DARK_TEXT_MUTED = "#9ca3af"
COLOR_DARK_PRIMARY = "#3b82f6"
COLOR_DARK_PRIMARY_HOVER = "#2563eb"
COLOR_DARK_PRIMARY_PRESSED = "#1d4ed8"
COLOR_DARK_DISABLED_BG = "#374151"
COLOR_DARK_DISABLED_TEXT = "#6b7280"
COLOR_DARK_SECONDARY_BG = "#1f2937"
COLOR_DARK_SECONDARY_HOVER = "#374151"
